#! /usr/bin/env python3

import argparse
from libsshtman import Client, FIFO_PATH

def parse_args():
    parser = argparse.ArgumentParser(description='SSH tunnel manager client')
    parser.add_argument('action', choices=('open', 'close', 'kill'), 
        help='open or close tunnel with a give name or kill dameon')
    parser.add_argument('tunnel_name', nargs='?', 
        help='name of a target tunnel', default=None)
    parser.add_argument('-l', '--local-port', type=int, 
        help='number of a local port to open tunnel to')
    parser.add_argument('-r', '--remote-port', type=int,
        help='number of a remote port to open tunnel from')
    parser.add_argument('-u', '--user', help='remote host username')
    parser.add_argument('-n', '--host', help='remote host')
    parser.add_argument('-s', '--ssh-port', help='remote ssh port', type=int)
    return parser.parse_args()


kwargs = vars(parse_args())
action = kwargs.pop('action')
tunnel_name = kwargs.pop('tunnel_name')

c = Client(FIFO_PATH)
c.perform_action(action, tunnel_name, **kwargs)

